dependencies:
- name: edgefs
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.2.96
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: hpdcloud
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.108
- name: hpdconnect
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.113
